/* ─────────────────────────────────────────────
   Khor Design Tokens  (JavaScript)
   Fuente de verdad para tokens consumidos en JS.
   
   v2.0: Migrado a CSS custom properties var()
   para soporte automático de Dark Mode.
   Los componentes que usen estos tokens en inline
   styles responderán automáticamente al toggle
   de tema .dark en el <html>.
   ───────────────────────────────────────────── */

export const khorTokens = {
  colors: {
    brand: {
      primary: 'var(--khor-primary)',
      primaryHover: 'var(--khor-primary-hover)',
      primaryActive: 'var(--khor-primary-active)',
      secondary: 'var(--khor-secondary)',
      secondaryHover: 'var(--khor-secondary-hover)',
      secondaryActive: 'var(--khor-secondary-active)',
      accent: 'var(--khor-accent)',
      accentHover: 'var(--khor-accent-hover)',
      accentActive: 'var(--khor-accent-active)',
      // Legacy alias
      navy: 'var(--khor-navy)',
      navyHover: 'var(--khor-navy-hover)',
      navyActive: 'var(--khor-navy-active)',
    },
    neutral: {
      50: 'var(--khor-neutral-50)',
      100: 'var(--khor-neutral-100)',
      200: 'var(--khor-neutral-200)',
      300: 'var(--khor-neutral-300)',
      400: 'var(--khor-neutral-400)',
      500: 'var(--khor-neutral-500)',
      600: 'var(--khor-neutral-600)',
      700: 'var(--khor-neutral-700)',
      800: 'var(--khor-neutral-800)',
      900: 'var(--khor-neutral-900)',
    },
    neutralSecondary: {
      50: 'var(--khor-neutral-secondary-50)',
      100: 'var(--khor-neutral-secondary-100)',
      200: 'var(--khor-neutral-secondary-200)',
      300: 'var(--khor-neutral-secondary-300)',
      400: 'var(--khor-neutral-secondary-400)',
      500: 'var(--khor-neutral-secondary-500)',
      600: 'var(--khor-neutral-secondary-600)',
      700: 'var(--khor-neutral-secondary-700)',
      800: 'var(--khor-neutral-secondary-800)',
      900: 'var(--khor-neutral-secondary-900)',
    },
    feedback: {
      success: 'var(--khor-success)',
      success50: 'var(--khor-success-50)',
      success100: 'var(--khor-success-100)',
      success200: 'var(--khor-success-200)',
      success300: 'var(--khor-success-300)',
      success400: 'var(--khor-success-400)',
      success500: 'var(--khor-success-500)',
      success600: 'var(--khor-success-600)',
      success700: 'var(--khor-success-700)',
      success800: 'var(--khor-success-800)',
      success900: 'var(--khor-success-900)',

      error: 'var(--khor-error)',
      error50: 'var(--khor-error-50)',
      error100: 'var(--khor-error-100)',
      error200: 'var(--khor-error-200)',
      error300: 'var(--khor-error-300)',
      error400: 'var(--khor-error-400)',
      error500: 'var(--khor-error-500)',
      error600: 'var(--khor-error-600)',
      error700: 'var(--khor-error-700)',
      error800: 'var(--khor-error-800)',
      error900: 'var(--khor-error-900)',

      warning: 'var(--khor-warning)',
      warning50: 'var(--khor-warning-50)',
      warning100: 'var(--khor-warning-100)',
      warning200: 'var(--khor-warning-200)',
      warning300: 'var(--khor-warning-300)',
      warning400: 'var(--khor-warning-400)',
      warning500: 'var(--khor-warning-500)',
      warning600: 'var(--khor-warning-600)',
      warning700: 'var(--khor-warning-700)',
      warning800: 'var(--khor-warning-800)',
      warning900: 'var(--khor-warning-900)',

      info: 'var(--khor-info)',
      info50: 'var(--khor-info-50)',
      info100: 'var(--khor-info-100)',
      info200: 'var(--khor-info-200)',
      info300: 'var(--khor-info-300)',
      info400: 'var(--khor-info-400)',
      info500: 'var(--khor-info-500)',
      info600: 'var(--khor-info-600)',
      info700: 'var(--khor-info-700)',
      info800: 'var(--khor-info-800)',
      info900: 'var(--khor-info-900)',

      teal: 'var(--khor-teal)',
      teal50: 'var(--khor-teal-50)',
      teal100: 'var(--khor-teal-100)',
      teal200: 'var(--khor-teal-200)',
      teal300: 'var(--khor-teal-300)',
      teal400: 'var(--khor-teal-400)',
      teal500: 'var(--khor-teal-500)',
      teal600: 'var(--khor-teal-600)',
      teal700: 'var(--khor-teal-700)',
      teal800: 'var(--khor-teal-800)',
      teal900: 'var(--khor-teal-900)',

      processing: 'var(--khor-feedback-processing)',
      volcano: 'var(--khor-feedback-volcano)',
      gold: 'var(--khor-feedback-gold)',
      lime: 'var(--khor-feedback-lime)',
      purple: 'var(--khor-feedback-purple)',
      white: '#FFFFFF',
      black: '#000000',
    },
  },
  typography: {
    fontPrimary: "var(--font-primary, 'Montserrat', sans-serif)",
    fontSecondary: "var(--font-secondary, 'Plus Jakarta Sans', sans-serif)",
    fontWeights: {
      light: 'var(--khor-font-weight-light)',
      regular: 'var(--khor-font-weight-regular)',
      medium: 'var(--khor-font-weight-medium)',
      semibold: 'var(--khor-font-weight-semibold)',
      bold: 'var(--khor-font-weight-bold)',
      extrabold: 'var(--khor-font-weight-extrabold)',
    },
    letterSpacing: {
      tighter: 'var(--khor-letter-spacing-tighter)',
      tight: 'var(--khor-letter-spacing-tight)',
      normal: 'var(--khor-letter-spacing-normal)',
      wide: 'var(--khor-letter-spacing-wide)',
      wider: 'var(--khor-letter-spacing-wider)',
    },
    h1: { size: 'var(--khor-font-size-h1)', weight: 'var(--khor-font-weight-bold)', lineHeight: 'var(--khor-line-height-heading)' },
    h2: { size: 'var(--khor-font-size-h2)', weight: 'var(--khor-font-weight-bold)', lineHeight: 'var(--khor-line-height-heading)' },
    h3: { size: 'var(--khor-font-size-h3)', weight: 'var(--khor-font-weight-semibold)', lineHeight: 'var(--khor-line-height-heading)' },
    h4: { size: 'var(--khor-font-size-h4)', weight: 'var(--khor-font-weight-semibold)', lineHeight: 'var(--khor-line-height-heading)' },
    h5: { size: 'var(--khor-font-size-h5)', weight: 'var(--khor-font-weight-semibold)', lineHeight: 'var(--khor-line-height-body)' },
    h6: { size: 'var(--khor-font-size-h6)', weight: 'var(--khor-font-weight-semibold)', lineHeight: 'var(--khor-line-height-body)' },
    bodyLg: { size: 'var(--khor-font-size-body-lg)', weight: 'var(--khor-font-weight-regular)', lineHeight: 'var(--khor-line-height-body)' },
    bodyMd: { size: 'var(--khor-font-size-body-md)', weight: 'var(--khor-font-weight-regular)', lineHeight: 'var(--khor-line-height-body)' },
    small: { size: 'var(--khor-font-size-body-sm)', weight: 'var(--khor-font-weight-medium)', lineHeight: 'var(--khor-line-height-body)' },
    display1: { size: 'var(--khor-font-size-display-1)', weight: 'var(--khor-font-weight-extrabold)', lineHeight: 'var(--khor-line-height-display)' },
    display2: { size: 'var(--khor-font-size-display-2)', weight: 'var(--khor-font-weight-extrabold)', lineHeight: 'var(--khor-line-height-display)' },
    caption: { size: 'var(--khor-font-size-body-sm)', weight: 'var(--khor-font-weight-regular)', lineHeight: 1.4 },
    overline: { size: 'var(--khor-font-size-body-xs)', weight: 'var(--khor-font-weight-semibold)', lineHeight: 1.2, letterSpacing: 'var(--khor-letter-spacing-wider)' },
  },
  sizing: {
    0: 'var(--khor-size-0)',
    1: 'var(--khor-size-1)',
    2: 'var(--khor-size-2)',
    3: 'var(--khor-size-3)',
    4: 'var(--khor-size-4)',
    5: 'var(--khor-size-5)',
    6: 'var(--khor-size-6)',
    8: 'var(--khor-size-8)',
    10: 'var(--khor-size-10)',
    12: 'var(--khor-size-12)',
    16: 'var(--khor-size-16)',
    20: 'var(--khor-size-20)',
    24: 'var(--khor-size-24)',
    32: 'var(--khor-size-32)',
    40: 'var(--khor-size-40)',
    48: 'var(--khor-size-48)',
    56: 'var(--khor-size-56)',
    64: 'var(--khor-size-64)',
    full: 'var(--khor-size-full)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 40,
  },
  shadows: {
    sm: 'var(--khor-shadow-sm)',
    md: 'var(--khor-shadow-md)',
    lg: 'var(--khor-shadow-lg)',
    xl: 'var(--khor-shadow-xl)',
    '2xl': 'var(--khor-shadow-2xl)',
    inner: 'var(--khor-shadow-inner)',
  },
  radius: {
    sm: 'var(--khor-radius-sm, 6px)' as unknown as number,
    md: 'var(--khor-radius-md, 8px)' as unknown as number,
    lg: 'var(--khor-radius-lg, 10px)' as unknown as number,
    xl: 'var(--khor-radius-xl, 14px)' as unknown as number,
  },
  layout: {
    sidebarWidth: 260,
    headerHeight: 64,
  },
  icon: {
    sm: 16,
    md: 20,
    lg: 24,
    strokeWidth: 2,
  },
  semantic: {
    action: {
      primary: { default: 'var(--khor-action-primary-default)', hover: 'var(--khor-action-primary-hover)', active: 'var(--khor-action-primary-active)' },
      secondary: { default: 'var(--khor-action-secondary-default)', hover: 'var(--khor-action-secondary-hover)', active: 'var(--khor-action-secondary-active)' },
      danger: { default: 'var(--khor-action-danger-default)', hover: 'var(--khor-action-danger-hover)', active: 'var(--khor-action-danger-active)' },
      ghost: { hover: 'var(--khor-action-ghost-hover)' },
      disabled: { bg: 'var(--khor-action-disabled-bg)', text: 'var(--khor-action-disabled-text)' },
    },
    surface: {
      page: 'var(--khor-surface-page)',
      card: 'var(--khor-surface-card)',
      raised: 'var(--khor-surface-raised)',
      overlay: 'var(--khor-surface-overlay)',
    },
    text: {
      primary: 'var(--khor-text-primary)',
      secondary: 'var(--khor-text-secondary)',
      muted: 'var(--khor-text-muted)',
      disabled: 'var(--khor-text-disabled)',
      onAction: 'var(--khor-text-on-action)',
      link: 'var(--khor-text-link)',
    },
    border: {
      default: 'var(--khor-border-default)',
      muted: 'var(--khor-border-muted)',
      strong: 'var(--khor-border-strong)',
      hover: 'var(--khor-border-hover)',
      focus: 'var(--khor-border-focus)',
      error: 'var(--khor-border-error)',
      disabled: 'var(--khor-border-disabled)',
    },
    focus: {
      ring: 'var(--khor-focus-ring)',
      ringWidth: 'var(--khor-focus-ring-width)',
      ringOffset: 'var(--khor-focus-ring-offset)',
    },
  },
  motion: {
    duration: { instant: 80, fast: 100, normal: 200, slow: 400, slower: 600 },
    easing: {
      standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
      enter: 'cubic-bezier(0, 0, 0.2, 1)',
      exit: 'cubic-bezier(0.4, 0, 1, 1)',
      spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    },
    spring: { stiffness: 300, damping: 30 },
  },
} as const;

/**
 * Static token values for contexts that can't use CSS variables 
 * (like Canvas, calculations, or third-party libraries requiring raw values).
 */
export const khorStaticTokens = {
  colors: {
    primary: '#E04D36',
    primaryHover: '#e8644f',
    secondary: '#051758',
    secondaryHover: '#0a2270',
    accent: '#FF9500',
    success: '#2E7D32',
    error: '#B71C1C',
    warning: '#E07800',
    info: '#1565C0',
    teal: '#0D7D7D',
    white: '#FFFFFF',
    black: '#000000',
    // Legacy alias
    navy: '#051758',
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
  },
  typography: {
    fontPrimary: "'Montserrat', sans-serif",
    fontSecondary: "'Plus Jakarta Sans', sans-serif",
  }
} as const;
